apiVersion: v1
kind: Service
metadata:
 name: mysql-fastapi-service
 labels:
 app: k8s-deployment
spec:
  type: ClusterIP
  selector:
  app: k8s-deployment
  ports:
   - port: 8001
     protocol: TCP      
     targetPort: 8000